# Generated by Django 5.1.5 on 2025-01-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('phno', models.CharField(max_length=15)),
                ('content', models.TextField()),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
    ]
